Install Python packages in the exact order as specified in the manifest file. Fixes #68.
MycroftAI/mycroft-skills-manager pull request #69
Opened 2020-03-22 10:04 UTC by rigved

2020-03-22 11:02 UTC, forslund commented
Thanks, this sounds like a good idea. I'll try to review tomorrow morning.

2020-03-23 10:23 UTC, forslund requested changes
Seems to work excellently! Just a small bike-shedding thing, I think it may be good to add a comment as to why we're doing the for-loop instead of just using a single pip call...so we don't go on a cleanup frenzy and revert this later.

2020-03-23 10:23 UTC, forslund commented on msm/skill_entry.py
> +            for dependent_python_package in self.dependent_python_packages:
Add a comment here that we're iterating over the individual packages installing them one by one to enforce the order specified in the manifest.

2020-03-25 10:56 UTC, rigved commented on msm/skill_entry.py
> +            for dependent_python_package in self.dependent_python_packages:
@forslund Thanks that's a great suggestion! I have added a comment explaining the code.

2020-03-27 12:23 UTC, forslund commented
Thanks @rigved, looks great! Merging!

2020-03-27 12:23 UTC, merged