fix #62
MycroftAI/mycroft-skills-manager pull request #70
Opened 2020-04-07 13:38 UTC by luca-vercelli

This is essentially https://github.com/MycroftAI/mycroft-skills-manager/pull/63/commits/6adf346c984bd1aa330239757ae158afafdfd125, taking in account of given suggestions

2020-04-07 14:25 UTC, forslund requested changes
Thanks, for contributing this fix. I flagged a minor caveat with the bare except. otherwise this looks good. To protect yourself and Mycroft we require you to sign a Contributor License Agreement (stating that you retain ownership of the contributed code but Mycroft is free to use it).

Please go to https://mycroft.ai/cla to start the process.

Once more thanks for picking up this issue!

2020-04-07 14:25 UTC, forslund commented on msm/skill_state.py
> +    except:
bare exceptions are generally frowned upon, make this `except Exception:`

2020-04-14 22:37 UTC, krisgesling commented
CLA received and looks like the feedback has been addressed. Are you happy for this to get merged Ake?

2020-05-04 10:09 UTC, forslund commented
Sorry for the late review. it works fine, thank you for taking care of this.

2020-05-04 10:32 UTC, merged